services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: elektrik_dukkani

  backend_dotnet:
    build:
      context: .
      dockerfile: backend-dotnet/Dockerfile
    depends_on:
      - mongo
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - DB_NAME=elektrik_dukkani
      - SECRET_KEY=change-me-in-prod
      - CORS_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "127.0.0.1:8001:8001"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    depends_on:
      - backend_dotnet
    restart: unless-stopped
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - REACT_APP_BACKEND_URL=http://localhost:8001
      - BROWSER=none
    ports:
      - "127.0.0.1:3000:3000"
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    command: sh -c "yarn install --frozen-lockfile || yarn install && yarn start"

volumes:
  mongo_data:
