services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: elektrik_dukkani

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    depends_on:
      - mongo
    restart: unless-stopped
    env_file:
      - backend/.env
    environment:
      # Ensure Python sends logs unbuffered
      - PYTHONUNBUFFERED=1
      # If .env overrides are missing, provide sensible defaults
      - MONGO_URL=mongodb://mongo:27017
      - DB_NAME=elektrik_dukkani
      - SECRET_KEY=${SECRET_KEY:-change-me-in-prod}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000,http://127.0.0.1:3000}
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./backend:/app/backend
    command: uvicorn backend.server:app --host 0.0.0.0 --port 8000

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - REACT_APP_BACKEND_URL=http://localhost:8000
      - BROWSER=none
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
  command: sh -c "yarn install && yarn start"

volumes:
  mongo_data:
